In [4]:
import numpy as np
import tensorly as tl

In [5]:
u = [3, 1, 2]
v = [4, 0, 3]
w = [2, 3, 4]

In [6]:
#dyadische Produkt
np.outer(u, v)

array([[12,  0,  9],
       [ 4,  0,  3],
       [ 8,  0,  6]])

In [7]:
#Skalar
np.dot(u,v)

18

In [8]:
A = [[3, 0, 4, 1], [2, 1, 3, 2]]
np.transpose(A)

array([[3, 2],
       [0, 1],
       [4, 3],
       [1, 2]])

In [7]:
#äusseres Produkt dreier Vektoren
np.einsum('i,j,k->ijk', u, v, w)

array([[[24, 36, 48],
        [ 0,  0,  0],
        [18, 27, 36]],

       [[ 8, 12, 16],
        [ 0,  0,  0],
        [ 6,  9, 12]],

       [[16, 24, 32],
        [ 0,  0,  0],
        [12, 18, 24]]])

In [3]:
#Kronecker-Produkt
tl.tenalg.kronecker((A, B))

NameError: name 'A' is not defined

In [ ]:
#Khatri-Rao-Produkt
tl.tenalg.khatri_rao((A, B))

In [ ]:
#Hadamard-Produkt
A*B

In [5]:
#Tensor berechnen
X = np.arange(24)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
X = X + 1     #Zahlen liegen in [0,23] --> +1 Zahlen liegen in [1,24]
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [7]:
X = X.reshape((3, 4, 2))
X

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [8]:
X[:,:,0]
X

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [9]:
X[:,:,1]
X

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [10]:
tl.unfold(X,0) #0.Mode Tensor

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [11]:
tl.unfold(X,1)  #1.Mode Tensor

array([[ 1,  2,  9, 10, 17, 18],
       [ 3,  4, 11, 12, 19, 20],
       [ 5,  6, 13, 14, 21, 22],
       [ 7,  8, 15, 16, 23, 24]])

In [12]:
tl.unfold(X,2)  #2.Mode Tensor

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24]])